//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("ShoppingList", Namespace="", IsNullable=false)]
public partial class ShoppingListType {
    
    private NoteType[] shoppingNoteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShoppingNote", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public NoteType[] ShoppingNote {
        get {
            return this.shoppingNoteField;
        }
        set {
            this.shoppingNoteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class NoteType {

    public NoteType() { }
    public NoteType(string name, string comment, double spentamount, System.DateTime dateofputchase)
    {
        Name = name;
        Comment = comment;
        Spentamount = spentamount;
        Dateofpurchase = dateofputchase;
    }

    private string nameField;
    
    private string commentField;
    
    private double spentamountField;
    
    private System.DateTime dateofpurchaseField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double Spentamount {
        get {
            return this.spentamountField;
        }
        set {
            this.spentamountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime Dateofpurchase {
        get {
            return this.dateofpurchaseField;
        }
        set {
            this.dateofpurchaseField = value;
        }
    }
}
